/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ChoreographyRouteImport } from './routes/choreography'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as TestimonialsRouteImport } from './routes/testimonials'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ChoreographyRoute = ChoreographyRouteImport.update({
  id: '/choreography',
  path: '/choreography',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/choreography': typeof ChoreographyRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/fitness': typeof FitnessRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/choreography': typeof ChoreographyRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/fitness': typeof FitnessRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/choreography': typeof ChoreographyRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/fitness': typeof FitnessRoute
  '/gallery': typeof GalleryRoute
  '/programs': typeof ProgramsRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/choreography'
    | '/contact'
    | '/events'
    | '/fitness'
    | '/gallery'
    | '/programs'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/choreography'
    | '/contact'
    | '/events'
    | '/fitness'
    | '/gallery'
    | '/programs'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/choreography'
    | '/contact'
    | '/events'
    | '/fitness'
    | '/gallery'
    | '/programs'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ChoreographyRoute: typeof ChoreographyRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FitnessRoute: typeof FitnessRoute
  GalleryRoute: typeof GalleryRoute
  ProgramsRoute: typeof ProgramsRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/choreography': {
      id: '/choreography'
      path: '/choreography'
      fullPath: '/choreography'
      preLoaderRoute: typeof ChoreographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ChoreographyRoute: ChoreographyRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FitnessRoute: FitnessRoute,
  GalleryRoute: GalleryRoute,
  ProgramsRoute: ProgramsRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
